[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
xcavate = "BwiZvqF34fsCHAgvHVpujHA2s3xrqGWJ6EmXHZhuFkiR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
